version: '3.7'

services:
   # Kafka
   kafka:
      image: wurstmeister/kafka:latest
      restart: always
      ports:
         - '9092:9092'
      environment:
         KAFKA_ADVERTISED_HOST_NAME: localhost
         KAFKA_CREATE_TOPICS: 'topic1:1:1,topic2:1:1'
         KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      volumes:
         - ./volumns/kafka_data:/var/lib/kafka

   # Zookeeper
   zookeeper:
      image: wurstmeister/zookeeper:latest
      restart: always
      ports:
         - '2181:2181'
      depends_on:
         - kafka
      volumes:
         - ./volumns/zookeeper_data:/var/lib/zookeeper

   # Mongodb
   mongodb:
      image: mongo:latest
      restart: always
      ports:
         - '27017:27017'
      volumes:
         - ./volumns/mongodb_data:/data/db

   # Redis
   redis:
      image: redis:latest
      restart: always
      ports:
         - '6379:6379'
      volumes:
         - ./volumns/redis_data:/data

      # Jaeger
   jaeger-all-in-one:
      image: jaegertracing/all-in-one:latest
      restart: always
      ports:
         - '16686:16686'
         - '14268'
         - '14250'

   # Collector
   otel-collector:
      image: otel/opentelemetry-collector:0.88.0
      restart: always
      command: ['--config=/etc/otel-collector-config.yml']
      volumes:
         - ./otel-collector-config.yml:/etc/otel-collector-config.yml
      ports:
         - '4317:4317' # OTLP gRPC receiver
         - '4318:4318' # OTLP HTTP receiver
         - '1888:1888' # pprof extension
         - '8888:8888' # Prometheus metrics exposed by the collector
         - '8889:8889' # Prometheus exporter metrics
         - '13133:13133' # health_check extension
         # - '55679:55679' # zpages extension
      depends_on:
         - jaeger-all-in-on
